remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Notes: https://pages.github.com/themes/
# Notes: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme
# PEACE 
# FreeAssange 
